# Generated by Django 3.0.8 on 2020-07-22 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, related_name='children', to='web.documents', verbose_name='父文章'),
        ),
    ]
